apiVersion: v1
kind: Service
metadata:
  name: {{ include "trees-webservice.fullname" . }}
  labels:
    {{- include "trees-webservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: eighty-eighty
  selector:
    {{- include "trees-webservice.selectorLabels" . | nindent 4 }}
