
name: CI Build and Publish Docker artifact

on:
  # run it on push to the default repository branch
  push:
    #branches: [main,workflows]
    tags:
      - 'v*.*.*'

jobs:
  build-trees-webservice-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build trees-webservice go Docker image
      run: |
        docker build . --tag ghcr.io/basigabri/trees-webservice:${GITHUB_REF#refs/*/}
        docker push ghcr.io/basigabri/trees-webservice:${GITHUB_REF#refs/*/}
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  helm-lint:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: build-trees-webservice-docker-image
    steps:
    - uses: actions/checkout@v2

    - name: Helm Lint
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint charts/trees-webservice
  
  deployment-on-k8s-cluster-with-helm:
    
    runs-on: 'ubuntu-latest'
    needs: helm-lint
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: 'Deploy'
      uses: 'glopezep/helm@v1.7.1'
      with:
        helm: helm3
        release: 'trees-webservice-${{ env.RELEASE_VERSION }}'
        namespace: 'trees'
        chart: 'charts/trees-webservice'
        token: '${{ secrets.K8S_QS_TOKEN }}'
        value-files: 'charts/trees-webservice/values.yaml'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
